apiVersion: apps/v1
kind: Deployment
metadata:
  name: ufo-service
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: ufo-service
  replicas: 1
  template:
    metadata:
      labels:
        run: ufo-service
    spec:
      containers:
      - name: ufo-service
        image: mvilliger/ufo-service:0.3
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: UFO_ADDRESS
          valueFrom:
            secretKeyRef:
                name: ufo
                key: UFO_ADDRESS
---
apiVersion: v1
kind: Service
metadata:
  name: ufo-service
  namespace: keptn
  labels:
    run: ufo-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: ufo-service
